[package]
name             = "ohkami_lib"
version          = "0.2.0"
edition          = "2021"
authors          = ["kanarus <kanarus786@gmail.com>"]
description      = "Internal library for ohkami - intuitive and declarative web framework"
documentation    = "https://docs.rs/ohkami"
homepage         = "https://crates.io/crates/ohkami"
repository       = "https://github.com/kana-rus/ohkami"
readme           = "../README.md"
keywords         = ["async", "http", "web", "server", "framework"]
categories       = ["asynchronous", "web-programming::http-server"]
license          = "MIT"

[dependencies]
serde            = { version = "1.0", features = ["derive"] }
percent-encoding = { version = "2.3" }
byte_reader      = { version = "2.0", features = ["text"] }