[workspace]
resolver = "2"
members  = [
    "ohkami",
    "ohkami_lib",
    "ohkami_macros",
]
exclude  = [
    "benches",
    "benches_glommio",
]

[workspace.dependencies]
byte_reader   = { version = "3.1", features = ["text"] }
serde         = { version = "1.0", features = ["derive"] }
