[workspace]
resolver = "2"
members  = [
    "ohkami",
    "ohkami_lib",
    "ohkami_macros"
]
exclude  = [
    "benches",
]

[workspace.dependencies]
byte_reader   = { version = "3.0", features = ["text"] }
serde         = { version = "1.0", features = ["derive"] }
