version: 3

vars:
  maybe_nightly: { sh: cargo version | grep -q 'nightly' && echo 'nightly' || echo ''  }

tasks:
  CI:
    deps:
      - task: test
      - task: check
      - task: bench:dryrun

  test:
    deps:
      - task: test:examples
      - task: test:doc
      - task: test:no_rt
      - for:  [tokio, async-std, smol, nio, glommio, worker]
        task: test:rt
        vars: { rt: '{{.ITEM}}' }

  check:
    deps:
      - task: check:no_rt
      - for:  [tokio, async-std, smol, nio, glommio]
        task: check:native_rt
        vars: { native_rt: '{{.ITEM}}' }
      - task: check:rt_worker

  bench:dryrun:
    status:
      - (! cargo version | grep -q 'nightly')
    cmds:
      - cd benches && cargo bench --features DEBUG --no-run
      - cd benches_rt/vs_actix-web && cargo check
      - for: [tokio, smol, nio, glommio]
        cmd: cd benches_rt/{{.ITEM}} && cargo check

  bench:
    status:
      - (! cargo version | grep -q 'nightly')
    dir: ./benches
    cmds:
      - task: bench:dryrun
      - cargo bench --features DEBUG

#### tests ####
  test:doc:
    dir: ./ohkami
    cmds:
      - cargo test --doc --features DEBUG,rt_tokio,sse,ws,{{.maybe_nightly}}

  test:examples:
    dir: examples
    cmds:
      - docker compose -f ./realworld/docker-compose.yml up -d
      - cd ./realworld && sleep 5 && sqlx migrate run
      - cargo test
      - docker compose -f ./realworld/docker-compose.yml down

  test:no_rt:
    dir: ./ohkami
    cmds:
      - cargo test --lib --features DEBUG,{{.maybe_nightly}}
      - cargo test --lib --features DEBUG,sse,ws,{{.maybe_nightly}}

  test:rt:
    dir: ./ohkami
    cmds:
      - cargo test --lib --features rt_{{.rt}},DEBUG,{{.maybe_nightly}}
      - cargo test --lib --features rt_{{.rt}},DEBUG,sse,ws,{{.maybe_nightly}}

#### checks ####
  # Assure buildability without "DEBUG" feature

  check:no_rt:
    vars:
      MAYBE_FEATURES_NIGHTLY:
        sh: cargo version | grep -q 'nightly' && echo '--features nightly' || echo ''
      MAYBE_FEATURES_NIGHTLY_full:
        sh: cargo version | grep -q 'nightly' && echo '--features nightly,sse,ws' || echo '--features sse,ws'
    dir: ./ohkami
    cmds:
      - cargo check --lib {{.MAYBE_FEATURES_NIGHTLY}}
      - cargo check --lib {{.MAYBE_FEATURES_NIGHTLY_full}}

  check:native_rt:
    dir: ./ohkami
    cmds:
      - cargo check --lib --features rt_{{.native_rt}},{{.maybe_nightly}}
      - cargo check --lib --features rt_{{.native_rt}},sse,{{.maybe_nightly}}
      - cargo check --lib --features rt_{{.native_rt}},ws,{{.maybe_nightly}}
      - cargo check --lib --features rt_{{.native_rt}},sse,ws,{{.maybe_nightly}}

  check:rt_worker:
    dir: ohkami
    cmds:
      - cargo check --target wasm32-unknown-unknown --lib --features rt_worker,{{.maybe_nightly}}
      - cargo check --target wasm32-unknown-unknown --lib --features rt_worker,sse,{{.maybe_nightly}}
      - cargo check --target wasm32-unknown-unknown --lib --features rt_worker,ws,{{.maybe_nightly}}
      - cargo check --target wasm32-unknown-unknown --lib --features rt_worker,sse,ws,{{.maybe_nightly}}
