version: '3'

tasks:
  CI:
    deps:
      - test
      - check
      - bench_dryrun

  test:
    deps:
      - test_doc
      - test_examples
      - test_no_rt
      - test_rt_tokio
      - test_rt_async-std
      - test_rt_smol
      - test_rt_glommio
      - test_rt_worker

  check:
    deps:
      - check_no_rt
      - check_rt_tokio
      - check_rt_async-std
      - check_rt_smol
      - check_rt_glommio
      - check_rt_worker

  bench_dryrun:
    cmds:
      - cd benches && cargo bench --features DEBUG --no-run
      - cd benches && cargo check
      - cd benches_rt/glommio && cargo check
      - cd benches_rt/smol && cargo check
      - cd benches_rt/tokio && cargo check
      - cd benches_rt/vs_actix-web && cargo check

  bench:
    dir: benches
    cmds:
      - cargo bench --features DEBUG

#### tests ####
  test_doc:
    vars:
      MAYBE_NIGHTLY:
        sh: cargo version | grep -q 'nightly' && echo 'nightly' || echo ''
    dir: ohkami
    cmds:
      - cargo test --doc --features DEBUG,rt_tokio,sse,ws,{{.MAYBE_NIGHTLY}}

  test_examples:
    dir: examples
    cmds:
      - docker compose -f ./realworld/docker-compose.yml up -d
      - cd ./realworld && sleep 5 && sqlx migrate run
      - cargo test
      - docker compose -f ./realworld/docker-compose.yml down

  test_no_rt:
    vars:
      MAYBE_NIGHTLY:
        sh: cargo version | grep -q 'nightly' && echo 'nightly' || echo ''
    dir: ohkami
    cmds:
      - cargo test --lib --features DEBUG,{{.MAYBE_NIGHTLY}}
      - cargo test --lib --features DEBUG,sse,ws,{{.MAYBE_NIGHTLY}}

  test_rt_tokio:
    vars:
      MAYBE_NIGHTLY:
        sh: cargo version | grep -q 'nightly' && echo 'nightly' || echo ''
    dir: ohkami
    cmds:
      - cargo test --lib --features rt_tokio,DEBUG,{{.MAYBE_NIGHTLY}}
      - cargo test --lib --features rt_tokio,DEBUG,sse,ws,{{.MAYBE_NIGHTLY}}
      - cargo test --lib --features rt_tokio,DEBUG,graceful,{{.MAYBE_NIGHTLY}}

  test_rt_async-std:
    vars:
      MAYBE_NIGHTLY:
        sh: cargo version | grep -q 'nightly' && echo 'nightly' || echo ''
    dir: ohkami
    cmds:
      - cargo test --lib --features rt_async-std,DEBUG,{{.MAYBE_NIGHTLY}}
      - cargo test --lib --features rt_async-std,DEBUG,sse,ws,{{.MAYBE_NIGHTLY}}

  test_rt_smol:
    vars:
      MAYBE_NIGHTLY:
        sh: cargo version | grep -q 'nightly' && echo 'nightly' || echo ''
    dir: ohkami
    cmds:
      - cargo test --lib --features rt_smol,DEBUG,{{.MAYBE_NIGHTLY}}
      - cargo test --lib --features rt_smol,DEBUG,sse,ws,{{.MAYBE_NIGHTLY}}

  test_rt_glommio:
    vars:
      MAYBE_NIGHTLY:
        sh: cargo version | grep -q 'nightly' && echo 'nightly' || echo ''
    dir: ohkami
    cmds:
      - cargo test --lib --features rt_glommio,DEBUG,{{.MAYBE_NIGHTLY}}
      - cargo test --lib --features rt_glommio,DEBUG,sse,ws,{{.MAYBE_NIGHTLY}}

  test_rt_worker:
    vars:
      MAYBE_NIGHTLY:
        sh: cargo version | grep -q 'nightly' && echo 'nightly' || echo ''
    dir: ohkami
    cmds:
      - cargo test --lib --features rt_worker,DEBUG,{{.MAYBE_NIGHTLY}}
      - cargo test --lib --features rt_worker,DEBUG,sse,ws,{{.MAYBE_NIGHTLY}}

#### checks ####
  # Assure buildability without "DEBUG" feature

  check_no_rt:
    vars:
      MAYBE_FEATURES_NIGHTLY:
        sh: cargo version | grep -q 'nightly' && echo '--features nightly' || echo ''
      MAYBE_FEATURES_NIGHTLY_full:
        sh: cargo version | grep -q 'nightly' && echo '--features nightly,sse,ws' || echo '--features testing'
    dir: ohkami
    cmds:
      - cargo check --lib {{.MAYBE_FEATURES_NIGHTLY}}
      - cargo check --lib {{.MAYBE_FEATURES_NIGHTLY_full}}

  check_rt_tokio:
    vars:
      MAYBE_NIGHTLY:
        sh: cargo version | grep -q 'nightly' && echo 'nightly' || echo ''
    dir: ohkami
    cmds:
      - cargo check --lib --features rt_tokio,{{.MAYBE_NIGHTLY}}
      - cargo check --lib --features rt_tokio,ip,{{.MAYBE_NIGHTLY}}
      - cargo check --lib --features rt_tokio,sse,{{.MAYBE_NIGHTLY}}
      - cargo check --lib --features rt_tokio,sse,ws,{{.MAYBE_NIGHTLY}}
      - cargo check --lib --features rt_tokio,graceful,{{.MAYBE_NIGHTLY}}
      - cargo check --lib --features rt_tokio,graceful,ip,{{.MAYBE_NIGHTLY}}

  check_rt_async-std:
    vars:
      MAYBE_NIGHTLY:
        sh: cargo version | grep -q 'nightly' && echo 'nightly' || echo ''
    dir: ohkami
    cmds:
      - cargo check --lib --features rt_async-std,{{.MAYBE_NIGHTLY}}
      - cargo check --lib --features rt_async-std,ip,{{.MAYBE_NIGHTLY}}
      - cargo check --lib --features rt_async-std,sse,{{.MAYBE_NIGHTLY}}
      - cargo check --lib --features rt_async-std,sse,ws,{{.MAYBE_NIGHTLY}}

  check_rt_smol:
    vars:
      MAYBE_NIGHTLY:
        sh: cargo version | grep -q 'nightly' && echo 'nightly' || echo ''
    dir: ohkami
    cmds:
      - cargo check --lib --features rt_smol,{{.MAYBE_NIGHTLY}}
      - cargo check --lib --features rt_smol,ip,{{.MAYBE_NIGHTLY}}
      - cargo check --lib --features rt_smol,sse,{{.MAYBE_NIGHTLY}}
      - cargo check --lib --features rt_smol,sse,ws,{{.MAYBE_NIGHTLY}}

  check_rt_glommio:
    vars:
      MAYBE_NIGHTLY:
        sh: cargo version | grep -q 'nightly' && echo 'nightly' || echo ''
    dir: ohkami
    cmds:
      - cargo check --lib --features rt_glommio,{{.MAYBE_NIGHTLY}}
      - cargo check --lib --features rt_glommio,ip,{{.MAYBE_NIGHTLY}}
      - cargo check --lib --features rt_glommio,sse,{{.MAYBE_NIGHTLY}}
      - cargo check --lib --features rt_glommio,sse,ws,{{.MAYBE_NIGHTLY}}

  check_rt_worker:
    vars:
      MAYBE_NIGHTLY:
        sh: cargo version | grep -q 'nightly' && echo 'nightly' || echo ''
    dir: ohkami
    cmds:
      - cargo check --target wasm32-unknown-unknown --lib --features rt_worker,{{.MAYBE_NIGHTLY}}
      - cargo check --target wasm32-unknown-unknown --lib --features rt_worker,sse,ws,{{.MAYBE_NIGHTLY}}
