version: '3'

tasks:
  test:
    deps:
      - test_doc
      - test_rt_tokio
      - test_rt_tokio_with_custom-header
      - test_rt_async-std
      - test_rt_async-std_with_custom-header
      - test_examples

  check:
    deps:
      - check_rt_tokio
      - check_rt_async-std

  bench_dryrun:
    dir: benches
    cmds:
      - cargo bench --no-run

  bench:
    dir: benches
    cmds:
      - cargo bench

#### tests ####
  test_doc:
    dir: ohkami
    cmds:
      - cargo test --doc --features DEBUG,rt_tokio
      - cargo test --doc --features DEBUG,rt_tokio,custom-header

  test_rt_tokio:
    dir: ohkami
    cmds:
      - cargo test --lib --no-default-features --features DEBUG,rt_tokio
      - cargo test --lib --no-default-features --features DEBUG,rt_tokio,testing
  test_rt_tokio_with_custom-header:
    dir: ohkami
    cmds:
      - cargo test --lib --no-default-features --features DEBUG,custom-header,rt_tokio
      - cargo test --lib --no-default-features --features DEBUG,custom-header,rt_tokio,testing

  test_rt_async-std:
    dir: ohkami
    cmds:
      - cargo test --lib --no-default-features --features DEBUG,rt_async-std
      - cargo test --lib --no-default-features --features DEBUG,rt_async-std,testing
  test_rt_async-std_with_custom-header:
    dir: ohkami
    cmds:
      - cargo test --lib --no-default-features --features DEBUG,custom-header,rt_async-std
      - cargo test --lib --no-default-features --features DEBUG,custom-header,rt_async-std,testing

  test_examples:
    dir: examples
    cmds:
      - docker compose -f ./realworld/docker-compose.yml up -d
      - cd ./realworld && sleep 5 && sqlx migrate run
      - cargo test
      - docker compose -f ./realworld/docker-compose.yml down

#### checks ####
  # Assure buildability without "DEBUG" feature

  check_rt_tokio:
    dir: ohkami
    cmds:
      - cargo check --lib --no-default-features --features rt_tokio
      - cargo check --lib --no-default-features --features rt_tokio,testing
      - cargo check --lib --no-default-features --features custom-header,rt_tokio
      - cargo check --lib --no-default-features --features custom-header,rt_tokio,testing

  check_rt_async-std:
    dir: ohkami
    cmds:
      - cargo check --lib --no-default-features --features rt_async-std
      - cargo check --lib --no-default-features --features rt_async-std,testing
      - cargo check --lib --no-default-features --features custom-header,rt_async-std
      - cargo check --lib --no-default-features --features custom-header,rt_async-std,testing
