version: '3'

tasks:
  test:
    deps:
      - test_doc
      - test_examples
      - test_no_rt
      - test_rt_tokio
      - test_rt_async-std
      - test_rt_worker

  check:
    deps:
      - check_no_rt
      - check_rt_tokio
      - check_rt_async-std
      - check_rt_worker

  bench_dryrun:
    dir: benches
    cmds:
      - cargo bench --features DEBUG --no-run
      - cargo check --bin hello

  bench:
    dir: benches
    cmds:
      - cargo bench --features DEBUG

#### tests ####
  test_doc:
    dir: ohkami
    cmds:
      - cargo test --doc --features DEBUG,rt_tokio
      - cargo test --doc --features DEBUG,rt_tokio

  test_examples:
    dir: examples
    cmds:
      - docker compose -f ./realworld/docker-compose.yml up -d
      - cd ./realworld && sleep 5 && sqlx migrate run
      - cargo test
      - docker compose -f ./realworld/docker-compose.yml down

  test_no_rt:
    vars:
      MAYBE_NIGHTLY:
        sh: cargo version | grep -q 'nightly' && echo 'nightly' || echo ''
    dir: ohkami
    cmds:
      - cargo test --lib --no-default-features --features DEBUG,{{.MAYBE_NIGHTLY}}
      - cargo test --lib --no-default-features --features DEBUG,testing,{{.MAYBE_NIGHTLY}}

  test_rt_tokio:
    vars:
      MAYBE_NIGHTLY:
        sh: cargo version | grep -q 'nightly' && echo 'nightly' || echo ''
    dir: ohkami
    cmds:
      - cargo test --lib --no-default-features --features rt_tokio,DEBUG,{{.MAYBE_NIGHTLY}}
      - cargo test --lib --no-default-features --features rt_tokio,DEBUG,testing,{{.MAYBE_NIGHTLY}}

  test_rt_async-std:
    vars:
      MAYBE_NIGHTLY:
        sh: cargo version | grep -q 'nightly' && echo 'nightly' || echo ''
    dir: ohkami
    cmds:
      - cargo test --lib --no-default-features --features rt_async-std,DEBUG,{{.MAYBE_NIGHTLY}}
      - cargo test --lib --no-default-features --features rt_async-std,DEBUG,testing,{{.MAYBE_NIGHTLY}}

  test_rt_worker:
    vars:
      MAYBE_NIGHTLY:
        sh: cargo version | grep -q 'nightly' && echo 'nightly' || echo ''
    dir: ohkami
    cmds:
      - cargo test --lib --no-default-features --features rt_worker,DEBUG,{{.MAYBE_NIGHTLY}}
      - cargo test --lib --no-default-features --features rt_worker,DEBUG,testing,{{.MAYBE_NIGHTLY}}

#### checks ####
  # Assure buildability without "DEBUG" feature

  check_no_rt:
    vars:
      MAYBE_NIGHTLY_FEATURES:
        sh: cargo version | grep -q 'nightly' && echo '--features nightly' || echo ''
      MAYBE_NIGHTLY_FEATURES_WITH_TESTING:
        sh: cargo version | grep -q 'nightly' && echo '--features nightly,testing' || echo '--features testing'
    dir: ohkami
    cmds:
      - cargo check --lib --no-default-features {{.MAYBE_NIGHTLY_FEATURES}}
      - cargo check --lib --no-default-features {{.MAYBE_NIGHTLY_FEATURES_WITH_TESTING}}

  check_rt_tokio:
    vars:
      MAYBE_NIGHTLY:
        sh: cargo version | grep -q 'nightly' && echo 'nightly' || echo ''
    dir: ohkami
    cmds:
      - cargo check --lib --no-default-features --features rt_tokio,{{.MAYBE_NIGHTLY}}
      - cargo check --lib --no-default-features --features rt_tokio,testing,{{.MAYBE_NIGHTLY}}

  check_rt_async-std:
    vars:
      MAYBE_NIGHTLY:
        sh: cargo version | grep -q 'nightly' && echo 'nightly' || echo ''
    dir: ohkami
    cmds:
      - cargo check --lib --no-default-features --features rt_async-std,{{.MAYBE_NIGHTLY}}
      - cargo check --lib --no-default-features --features rt_async-std,testing,{{.MAYBE_NIGHTLY}}

  check_rt_worker:
    vars:
      MAYBE_NIGHTLY:
        sh: cargo version | grep -q 'nightly' && echo 'nightly' || echo ''
    dir: ohkami
    cmds:
      - cargo check --lib --no-default-features --features rt_worker,{{.MAYBE_NIGHTLY}}
      - cargo check --lib --no-default-features --features rt_worker,testing,{{.MAYBE_NIGHTLY}}
