[package]
name    = "openapi"
version = "0.1.0"
edition = "2021"

[dependencies]
ohkami  = { workspace = true }
tokio   = { workspace = true }

[features]
default = ["ohkami/openapi"]
DEBUG   = ["ohkami/DEBUG"]
