[package]
name          = "ohkami"
version       = "0.20.0"
edition       = "2021"
authors       = ["kanarus <kanarus786@gmail.com>"]
description   = "Build web app in intuitive and declarative code"
documentation = "https://docs.rs/ohkami"
homepage      = "https://crates.io/crates/ohkami"
repository    = "https://github.com/ohkami-rs/ohkami"
readme        = "../README.md"
keywords      = ["async", "http", "web", "server", "framework"]
categories    = ["asynchronous", "web-programming::http-server", "network-programming", "wasm"]
license       = "MIT"


[package.metadata.docs.rs]
features      = ["rt_tokio", "nightly", "sse", "ws"]


[dependencies]
ohkami_lib    = { version = "=0.2.5", path = "../ohkami_lib" }
ohkami_macros = { version = "=0.8.0", path = "../ohkami_macros" }

tokio         = { version = "1",   optional = true, features = ["net", "rt", "io-util", "time"] }
async-std     = { version = "1",   optional = true }
smol          = { version = "2",   optional = true }
glommio       = { version = "0.9", optional = true }
worker        = { version = "0.3", optional = true }

byte_reader   = { workspace = true }
serde         = { workspace = true }

serde_json    = { version = "1.0" }
rustc-hash    = { version = "2.0" }

hmac          = { version = "0.12", default-features = false }
sha2          = { version = "0.10", default-features = false }
sha1          = { version = "0.10", optional = true, default-features = false }

num_cpus      = { version = "1.16", optional = true }
futures-util  = { version = "0.3",  optional = true, default-features = false, features = ["io"] }


[features]
default       = ["testing"]

rt_tokio      = ["__rt__", "__rt_native__", "dep:tokio"]
rt_async-std  = ["__rt__", "__rt_native__", "dep:async-std"]
rt_smol       = ["__rt__", "__rt_native__", "dep:smol",    "dep:futures-util"]
rt_glommio    = ["__rt__", "__rt_native__", "dep:glommio", "dep:futures-util", "dep:num_cpus"]
rt_worker     = ["__rt__", "dep:worker",  "ohkami_macros/worker"]

nightly       = []
testing       = []
sse           = ["ohkami_lib/stream"]
ws            = ["dep:sha1"]
graceful      = ["dep:futures-util", "futures-util/async-await-macro", "ohkami_lib/signal"]
ip            = []

##### internal #####
__rt__        = []
__rt_native__ = []

##### DEBUG #####
DEBUG = [
    "tokio?/macros",
    "tokio?/rt-multi-thread",
    "async-std?/attributes",
]
#default = [
#    "nightly",
#    "testing",
#    "sse",
#    "ws",
#    "ip",
#    "graceful",
#    "rt_tokio",
#    #"rt_async-std",
#    #"rt_smol",
#    #"rt_glommio",
#    #"rt_worker",
#    "DEBUG",
#]