[package]
name          = "ohkami"
version       = "0.21.0"
edition       = "2021"
authors       = ["kanarus <kanarus786@gmail.com>"]
description   = "Build web app in intuitive and declarative code"
documentation = "https://docs.rs/ohkami"
homepage      = "https://crates.io/crates/ohkami"
repository    = "https://github.com/ohkami-rs/ohkami"
readme        = "../README.md"
keywords      = ["async", "http", "web", "server", "framework"]
categories    = ["asynchronous", "web-programming::http-server", "network-programming", "wasm"]
license       = "MIT"


[package.metadata.docs.rs]
features      = ["rt_tokio", "nightly", "sse", "ws"]


[dependencies]
ohkami_lib    = { version = "=0.21.0", path = "../ohkami_lib" }
ohkami_macros = { version = "=0.21.0", path = "../ohkami_macros" }

tokio         = { version = "1",   optional = true, features = ["rt", "net", "time"] }
async-std     = { version = "1",   optional = true }
smol          = { version = "2",   optional = true }
glommio       = { version = "0.9", optional = true }
worker        = { version = "0.4", optional = true }

byte_reader   = { workspace = true }
serde         = { workspace = true }

serde_json    = { version = "1.0" }

base64        = { version = "0.22" }
hmac          = { version = "0.12", default-features = false }
sha2          = { version = "0.10", default-features = false }

num_cpus      = { version = "1.16", optional = true }
futures-util  = { version = "0.3",  optional = true, default-features = false, features = ["io", "async-await-macro"] }
mews          = { version = "0.1", optional = true }


[features]
default       = ["testing"]

rt_tokio      = ["__rt__", "__rt_native__", "dep:tokio",     "tokio/io-util", "tokio/macros",    "ohkami_lib/signal", "mews?/tokio"]
rt_async-std  = ["__rt__", "__rt_native__", "dep:async-std", "dep:futures-util",                 "ohkami_lib/signal", "mews?/async-std"]
rt_smol       = ["__rt__", "__rt_native__", "dep:smol",      "dep:futures-util",                 "ohkami_lib/signal", "mews?/smol"]
rt_glommio    = ["__rt__", "__rt_native__", "dep:glommio",   "dep:futures-util", "dep:num_cpus", "ohkami_lib/signal", "mews?/glommio"]
rt_worker     = ["__rt__", "dep:worker", "ohkami_macros/worker"]

nightly       = []
testing       = []
sse           = ["ohkami_lib/stream"]
ws            = ["ohkami_lib/stream", "dep:mews"]

##### internal #####
__rt__        = []
__rt_native__ = []

##### DEBUG #####
DEBUG = [
    "tokio?/rt-multi-thread",
    "async-std?/attributes",
]
#default = [
#    "nightly",
#    "testing",
#    "sse",
#    "ws",
#    #"rt_tokio",
#    #"rt_async-std",
#    #"rt_smol",
#    #"rt_glommio",
#    "rt_worker",
#    "DEBUG",
#]