[package]
name       = "ohkami_benches"
version    = "0.0.0"
edition    = "2021"
authors    = ["kanarus <kanarus786@gmail.com>"]

[dependencies]
ohkami     = { version = "0.16.0", path = "../ohkami", features = ["rt_tokio", "DEBUG"] }
ohkami_lib = { version = "0.2.0", path = "../ohkami_lib" }
http       = "1.0.0"
rustc-hash = "1.1"
bytes      = "1.5.0"