name: auto_approve
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

jobs:
  auto_approve:
    runs-on: ubuntu-latest
    steps:
      - name: hello
        run:  echo 'not skipped'
#    if: |
#      github.event.pull_request.user.login == github.repository_owner &&
#      !github.event.pull_request.draft
#    permissions:
#      pull-requests: write
#    runs-on: ubuntu-latest
#    steps:
#      - uses: hmarr/auto-approve-action@v4
